_target_: pytorch_lightning.Trainer

# Devices
devices: 2
strategy: ddp
accelerator: cpu
sync_batchnorm: true

# Train scheduling
min_epochs: 10
max_epochs: 10
limit_train_batches: 10
limit_val_batches: 10
limit_test_batches: 10