_target_: pytorch_lightning.Trainer

# Training
max_epochs: ???
min_epochs: ${trainer.max_epochs}
limit_train_batches: 10000
accumulate_grad_batches: 1
reload_dataloaders_every_n_epochs: 1

# Validation
log_every_n_steps: 100
num_sanity_val_steps: 10

# Misc
enable_progress_bar: true
enable_checkpointing: true
enable_model_summary: true
