defaults:
  # Experiment related
  - experiment: audio2text_adafactor_auto_lr
  - experiment/net: lilac

  # Data related
  - data: audio2text
  - data/datasets@data.train_datasets:
    - clotho_dev
  - data/datasets@data.val_datasets:
    - clotho_dev

  # Trainer
  - trainer: default
  - callbacks:
    - train_proj_only

  - _self_
  
filter_warnings: true
print_config: false

paths:
  output_dir: ???
  datasets_root_dir: "../../../../../Datasets/speech"

data:
  train_batch_size: 2
  val_batch_size: 2

trainer:
  max_epochs: 40
  accumulate_grad_batches: 16