defaults:
  # Experiment related
  - experiment: audio2text
  - experiment/net: lilac
  - experiment/optimizer: adamw
  - experiment/scheduler: cosine_annealing_with_warmup

  # Data related
  - data: audio2text
  - data/datasets@data.train_datasets:
    - clotho_dev
  - data/datasets@data.val_datasets:
    - clotho_dev

  # Trainer
  - trainer: default
  - callbacks:
    - train_proj_only

  - _self_
  
filter_warnings: true
print_config: true

paths:
  output_dir: ???
  datasets_root_dir: "../../../../../Datasets/speech"

data:
  train_batch_size: 2
  val_batch_size: 2

trainer:
  min_epochs: 40
  max_epochs: 40
  accumulate_grad_batches: 16