defaults:
  - experiment: audio2text_adafactor_auto_lr
  - experiment/net: lilac

  # Data
  - data: audio2text
  - data/datasets@data.train_datasets:
    - clotho_dev
  - data/datasets@data.val_datasets:
    - clotho_dev

  - trainer: default
  - logger: tensorboard
  - callbacks: [train_proj_only]
  - debug: null
  - extras: low_resource_mode
  - _self_

  # Overrides
  - override experiment/net/decoder: random_llama


paths:
  output_dir: ???
  datasets_root_dir: "../../../../../Datasets/speech"

trainer:
  max_epochs: 10